from __future__ import annotations

import json
from pathlib import Path

import pytest

from worldshepherd_sara.sbom_cli import (
    SBOM_EVIDENCE_SCHEMA,
    EVIDENCE_STATUS,
    build_sbom_evidence,
    main,
    parse_dependency_freeze,
)


def test_parse_dependency_freeze_normalizes_components(tmp_path: Path) -> None:
    freeze = tmp_path / "dependency-freeze.txt"
    freeze.write_text(
        "\n".join(
            [
                "# generated by CI",
                "fastapi==0.141.1",
                "worldshepherd_sara==0.1.0",
                "-e file:///work/Sara_pro/deployments/sara_verified_local_v1#egg=worldshepherd-sara",
                "",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    components = parse_dependency_freeze(freeze)
    refs = {component["bom-ref"] for component in components}

    assert "pkg:pypi/fastapi@0.141.1" in refs
    assert "pkg:pypi/worldshepherd-sara@0.1.0" in refs
    assert "pkg:pypi/worldshepherd-sara" in refs


def test_build_sbom_evidence_records_claims_boundary_and_inputs(tmp_path: Path) -> None:
    freeze = tmp_path / "dependency-freeze.txt"
    pyproject = tmp_path / "pyproject.toml"
    runtime = tmp_path / "constraints-runtime.txt"
    ci = tmp_path / "constraints-ci.txt"
    freeze.write_text("fastapi==0.141.1\nuvicorn==0.52.4\n", encoding="utf-8")
    pyproject.write_text("[project]\nname='worldshepherd-sara'\n", encoding="utf-8")
    runtime.write_text("fastapi==0.141.1\n", encoding="utf-8")
    ci.write_text("pytest==8.4.2\n", encoding="utf-8")

    sbom, summary = build_sbom_evidence(
        dependency_freeze=freeze,
        pyproject=pyproject,
        runtime_constraints=runtime,
        ci_constraints=ci,
        repository="Bdavis1390/Sara_pro",
        commit_sha="abc123",
        operator="github-actions",
        executed_utc="2026-09-01T18:00:00Z",
    )

    assert sbom["bomFormat"] == "CycloneDX"
    assert sbom["specVersion"] == "1.5"
    assert summary["schema"] == SBOM_EVIDENCE_SCHEMA
    assert summary["evidence_status"] == EVIDENCE_STATUS
    assert summary["component_count"] == 2
    assert summary["input_files"]["dependency_freeze"]["sha256"].startswith("sha256:")
    assert "does not establish a complete" in summary["claims_boundary"]
    assert "cmmc_conformity" in summary["not_claimed"]


def test_sbom_cli_writes_summary_and_bom(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.chdir(tmp_path)
    freeze = Path("dependency-freeze.txt")
    pyproject = Path("pyproject.toml")
    freeze.write_text("fastapi==0.141.1\npytest==8.4.2\n", encoding="utf-8")
    pyproject.write_text("[project]\nname='worldshepherd-sara'\n", encoding="utf-8")
    out_dir = Path("sbom_evidence_ci")

    exit_code = main(
        [
            "--dependency-freeze",
            str(freeze),
            "--pyproject",
            str(pyproject),
            "--out",
            str(out_dir),
            "--repository",
            "Bdavis1390/Sara_pro",
            "--commit-sha",
            "abc123",
            "--operator",
            "github-actions",
            "--executed-utc",
            "2026-09-01T18:01:00Z",
        ]
    )

    assert exit_code == 0
    sbom = json.loads((out_dir / "software-sbom.json").read_text(encoding="utf-8"))
    summary = json.loads((out_dir / "sbom-evidence-summary.json").read_text(encoding="utf-8"))
    assert sbom["components"][0]["name"] == "fastapi"
    assert summary["software_sbom_sha256"].startswith("sha256:")
    assert summary["summary_digest"].startswith("sha256:")


def test_sbom_cli_rejects_paths_outside_working_directory(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    workspace = tmp_path / "workspace"
    outside = tmp_path / "outside"
    workspace.mkdir()
    outside.mkdir()
    (outside / "dependency-freeze.txt").write_text("fastapi==0.141.1\n", encoding="utf-8")
    monkeypatch.chdir(workspace)

    with pytest.raises(ValueError, match="under working directory"):
        main(
            [
                "--dependency-freeze",
                str(outside / "dependency-freeze.txt"),
                "--out",
                "sbom_evidence_ci",
                "--commit-sha",
                "abc123",
            ]
        )


def test_sbom_generation_rejects_missing_dependency_freeze(tmp_path: Path) -> None:
    with pytest.raises(ValueError, match="dependency freeze file is required"):
        parse_dependency_freeze(tmp_path / "missing.txt")


def test_sbom_outputs_do_not_claim_formal_supply_chain_readiness(tmp_path: Path) -> None:
    freeze = tmp_path / "dependency-freeze.txt"
    freeze.write_text("fastapi==0.141.1\n", encoding="utf-8")
    sbom, summary = build_sbom_evidence(
        dependency_freeze=freeze,
        pyproject=None,
        runtime_constraints=None,
        ci_constraints=None,
        repository="Bdavis1390/Sara_pro",
        commit_sha="abc123",
        operator="github-actions",
        executed_utc="2026-09-01T18:02:00Z",
    )

    text = json.dumps({"sbom": sbom, "summary": summary}, sort_keys=True).lower()
    for forbidden in (
        "cmmc_certified",
        "nist_800_171_conformant",
        "slsa_level_3",
        "supplier_approved",
        "partner_validated",
        "field_validated",
        "hardware_validated",
    ):
        assert forbidden not in text
